import Head from "next/head";
import Image from "next/image";
import Hero from "@/components/Hero";
import Intro from "@/components/Intro";
import ContainerSizes from "@/components/Containers";
import Security from "@/components/Security";
import PickUp from "@/components/Pick-Up-Service";
import Contact from "@/components/Contact";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Blue Box Storage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <Hero />
        </div>
        <div>
          <Intro />
        </div>
        <div>
          <ContainerSizes />
        </div>
        <div>
          <Security />
        </div>
        <div>
          <PickUp />
        </div>
        <div>
          <Contact />
        </div>
      </div>
    </div>
  );
}
